services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2

image: gradle:jdk14

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew check --info

#test:
#  stage: test
#  script:
#    - ./gradlew check --info

pages:
  script:
  - ./gradlew docs
  - mkdir .public
  - cp -r docs/build/docs/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master


after_script:
  - echo "End CI"
