version: "3.9"
services:
  redis:
    image: "redis:6-alpine"
    ports:
      - "6379:6379"
  mongo:
    image: "mongo:4"
    ports:
      - "27017:27017"
    volumes:
      - ./.data/mongo:/data/db:rw
      - ./scripts/mongo:/docker-entrypoint-initdb.d:rw
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  prometheus_pushgateway:
    image: "prom/pushgateway:latest"
    ports:
      - "9091:9091"