spring:
  cloud:
    kubernetes:
      enabled: false
      
---
spring:
  config:
    activate:
      on-profile: TEST
  
  main:
    banner-mode: "off"
  
logging:
  level:
    root: OFF
    org.springframework: OFF
  
---
spring:
  config:
    activate:
      on-profile: LOCAL
  rabbitmq:
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        default.binder: rabbitmq
        main-out-0:
          destination: E.main
        jobResult-in-0:
          destination: E.main
          group: Q.job-results
      rabbit:
        bindings:
          main-out-0:
            producer:
              declare-exchange: false
              routing-key-expression: headers['routingKey']
          jobResult-in-0:
            consumer:
              declare-exchange: false
              bind-queue: false
              queue-name-group-only: true
      
management:
  endpoints.web.exposure.include: health,prometheus,info
  endpoint.prometheus.enabled: true