server:
   port: 8080

application:
   names:
      - Alice
      - Bob
      - Charlie
      - David

google.recaptcha:
  site-key: ${GOOGLE_RECAPTCHA_SITE_KEY}
  secret-key: ${GOOGLE_RECAPTCHA_SECRET_KEY}
  action-thresholds:
    HELLO: 0.5

management.health.probes.enabled: true

#management:
#  endpoints.web.exposure.include: health,prometheus,info,loggers,caches,metrics
#  endpoint:
#    health:
#      show-details: when-authorized
#      roles: ACTUATOR
#    prometheus.enabled: true
#    loggers.enabled: true
#    caches.enabled: true
#    metrics.enabled: true

#prometheus.pushmetrics.pushgateway.endpoint.url: http://localhost:9091

spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: ${MAIL_USERNAME}
spring.mail.password: ${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true

spring.servlet.multipart:
  enabled: false

springdoc:
   cache.disabled: true
   api-docs:
      enabled: true
   swagger-ui:
      enabled: false
   packages-to-scan: me.julb
   additional-properties:
      name: test
      version: 1.0.0-SNAPSHOT
      description: desc
      servers:
         - url: "http://localhost:8080"
           description: "Hello"
      authentication:
         authentication-headers:
            - display-name: header1
              header-name: X-Header-1
            - display-name: header2
              header-name: X-Header-2
