spring:
  cloud:
    kubernetes:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: NO_OUTPUT
  main:
    banner-mode: "off"
  
logging:
  level:
    root: OFF
    org.springframework: OFF
   
---
spring:
  config:
    activate:
      on-profile: TEST
  
  main:
    banner-mode: "off"
  
logging:
  level:
    root: OFF
    org.springframework: OFF
  
---
spring:
  config:
    activate:
      on-profile: LOCAL
  sleuth:
    baggage:
      remote-fields: x-request-id
      correlation-fields: x-request-id

info.test: lol

server:
  port: 9096

management:
  endpoints.web.exposure.include: health,prometheus,info
  endpoint.prometheus.enabled: true
  
application:
  local:
    metadata:
      name: localhost
    endpoint:
      url: http://localhost:9096

---

spring:
  config:
    activate:
      on-profile: OAS3

springdoc:
   cache.disabled: true
   api-docs:
      enabled: true
   swagger-ui:
      enabled: false
   packages-to-scan: me.julb
   additional-properties:
      name: ${build.name}
      version: ${build.version}
      description: desc
      servers:
         - url: "http://localhost:8080"
           description: "Hello"
      authentication:
         authentication-headers:
            - display-name: header1
              header-name: X-Header-1
            - display-name: header2
              header-name: X-Header-2
      extra-info:
        display-name: Ping API
        long-description: |
          # Hello API
        tags: abc,def,ghi

---
spring:
  config:
    activate:
      on-profile: DEV,INT,VAL,STG,PROD
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
      config:
        sources:
        - name: api-default-java
        - name: api-default-backend-java
        - name: ${APPLICATION_FULL_NAME}